os:
  - linux
  - osx

language: cpp
compiler: 
  - gcc
  - clang

before_script:
  - cmake --version
  - gcc --version
  - clang --version
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo apt-get install -y -q cmake libasound2-dev
  - mkdir build
  - cd build
  - cmake ../
  
script: make

after_script:
  - cd build
  - chmod +x test/Tests
  - test/Tests
