os:
  - linux
  - osx

language: cpp
compiler: gcc

before_script:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -y -q cmake libasound2-dev
  - mkdir build
  - cd build
  - cmake ../
  
script: make
