sudo: false
os:
  - linux
  - osx

language: cpp
compiler: 
  - gcc
  - clang

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
      - libasound2-dev

before_script:
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - mkdir build
  - cd build
  - cmake ../
  
script: make

after_script:
  - cd build
  - chmod +x test/Tests
  - test/Tests
