platform:
  - x86
  - x64
  
configuration:
  - Release

os:
  - Visual Studio 2015 RC
  
build_script:
  - md build
  - cd build
  - cmake -DBUILD_TESTING=YES -G"Visual Studio 14 2015" ..
  - cmake --build .
  
test_script:
  - '**\Tests.exe'

artifacts:
  - path: '**\OHMComm.exe'
