platform:
  - x86
  - x64
  
configuration:
  - Release

os:
  - Visual Studio 2015 RC
  
build_script:
  - md build
  - cd build
  - cmake -DBUILD_TESTING=ON -DTEST_OUTPUT_CONSOLE=ON -G"Visual Studio 14 2015" ..
  - cmake --build .
  
#test_script:
#  - .\build\test\Debug\Tests.exe

artifacts:
  - path: '**\OHMComm.exe'
    name: OHMComm-win-$(platform)

deploy:
- provider: GitHub
  description: 'Windows builds'
  draft: false
  prerelease: false
  auth_token:
    secure: Kttc7goEAF7pVbwGtg9M6PWeFXpaHOCZOsuyVioY7KPuJcGCjzy32F1I+yRRGK/q
  on:
    #branch: master
    appveyor_repo_tag: true
